#!/usr/bin/env bash
# This script configures Nginx on a server
# Configs: listen on port 80, redirect a page & return 'Hello World!' at /
apt-get update -y
apt-get install nginx -y
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/^\tserver_name _.*/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i '/^\tserver_name _.*/a \\terror_page 404 /error404.html;' /etc/nginx/sites-available/default
service nginx restart
