#!/usr/bin/env bash
# This scripty configs Nginx on server
apt-get update -y
apt-get install nginx -y
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "/^\tlocation \/ {.*/a \\\t \tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
sed -i '/^\tserver_name _.*/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i '/^\tserver_name _.*/a \\terror_page 404 /error404.html;' /etc/nginx/sites-available/default
service nginx restart
