#!/usr/bin/env bash
# another one of the same lol
while IFS=: read -r usr pass id gid inf hom shel
do
	echo "The user $usr is part of the $gid gang, lives in $hom and rides $shel. $id's place is protected by the passcode $pass, more info about the user here: $inf"
done < /etc/passwd
