#!/usr/bin/env bash
# this thing prints "Best School" ten times but "Hi" on 9th iteration

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
