#!/usr/bin/env bash
# Literally the same thing
pkill -f apache2
sudo -u nginx service nginx start > /dev/null 2>&1
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart > /dev/null 2>&1
